name: flutter_set_font
description: A sample command-line application.
version: 1.0.1

environment:
  sdk: '>=2.16.1 <3.0.0'



dependencies:
  recase: ^4.0.0


dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
